### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by kngu9** [Erronsing/LoLENetPacketDissector#1]
Hi! I am unable to compile this on Windows. Are there certain steps to achieve this?

**Comment by garthbjerk** [comment]
There's a bunch of tinkering around with some of the wireshark developer files. I wrote this for Ubuntu/Linux. Try it out on there or follow the tutorial for doing it on Windows. I have to warn you that it was much more of a pain on Windows. Here's the tutorial I used for environment setup: https://www.wireshark.org/docs/wsdg_html_chunked/ChDissectAdd.html and http://www.sewio.net/open-sniffer/develop/how-to-write-wireshark-dissector/.
